- assets/master/0400_master_daemonset.yaml
- assets/worker/0700_worker_daemonset.yaml
- manifests/0600_operator.yaml
- manifests/olm-catalog/4.2/image-references
- manifests/olm-catalog/4.2/nfd.v4.2.0.clusterserviceversion.yaml
- pkg/config/config.go
- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
Operand Image via Environment Variable
> Operand Image via Environment Variable

- assets/master/0400_master_daemonset.yaml
- assets/worker/0700_worker_daemonset.yaml
- manifests/0600_operator.yaml
- manifests/olm-catalog/4.2/image-references
- manifests/olm-catalog/4.2/nfd.v4.2.0.clusterserviceversion.yaml
- pkg/config/config.go
- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
Operand as a ENV variable, so that ART can replace operator/operand image.
> Operand as a ENV variable

- assets/worker/0600_worker_configmap.yaml
Configmap update to allow 02 PCI device class  per default.
> Bug  1732903: Configmap update

- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
- test/e2e/e2e_test.go
- vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
Various fixies for Updates of Resources already in the Cluster
> Bug 1733315: Various fixies for Updates of Resources already in the Cluster

- OWNERS
Adding sjug as additional reviewer.
> Bug 1753321: Update OWNERS

- assets/config/0110_namespace.yaml
- manifests/olm-catalog/4.2/nfd.v4.2.0.clusterserviceversion.yaml
- manifests/olm-catalog/nfd.package.yaml
- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_resources.go
- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go
This PR fixes several bugs for NFD.
- Updated CSV with correct version
- Updated CSV and added contact email (`operator-courier` was not complaining)
- Added new state to configure Namespace
- Added namespace to CR for confiruation where to install the operand
> Csv config fixes

- manifests/olm-catalog/4.3/nfd.crd.yaml
oc explain nodefeaturediscoveries.nfd.openshift.io cmd returns Description field"
> Bug 1769455: oc explain nodefeaturediscoveries.nfd.openshift.io 

- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controller.go
Added more Watcher for secondary resource
> Bug 1782948: Added more Watcher for secondary resource

- pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controller.go
Added more Watcher for secondary resource
> Bug 1775849: [release-4.3] Added more Watcher for secondary resource

- Dockerfile.rhel7
- Makefile
On line 38 fix file name 0100namespace.yaml -> 0100namespace.yaml
> Bug 1801367: Fix test-e2e make target

- LICENSE
> add LICENSE apache 2.0

- Makefile
> Fix Makefile variables declaration

- OWNERS
> Add dagrayvid to reviewers

- README.md
The Makefile is not in cluster-nfd-operator/manifests but cluster-nfd-operator/.
> Change the make deploy folder

- manifests/olm-catalog/4.5/nfd.crd.yaml
fix https://github.com/openshift/cluster-nfd-operator/issues/82
> nfd.crd.yaml: remove duplicate version

- manifests/0500_crd.yaml
one extra fix to update the master fast-forward to 4.6 
> Fix fastforward master

- pkg/config/config.go
> fix default operand image on config.go

- OWNERS
> add kpouget to OWNERS file

- manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
It is causing validation to fail.
> CSV: remove duplicate `version` key

- manifests/0500_crd.yaml
> update crd softLink

- assets/worker/0700_worker_daemonset.yaml
> Bug 1897346: NFD worker pods not scheduled on a 3 node master/worker cluster

- manifests/olm-catalog/4.7/nfd.crd.yaml
- manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml
- manifests/olm-catalog/art.yaml
- manifests/olm-catalog/nfd.package.yaml
> Bug 1908492: Update OLM catalog to new CRD and CSV

- manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml
> [release-4.7] Bug 1914869:  fix alm-example

- manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml
> Bug 1916010: fix olm skip range 

- manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml
> Bug 1914869: Fix alm-example json parsing

- assets/worker/0700_worker_daemonset.yaml
As discussed in https://github.com/openshift/cluster-nfd-operator/pull/111
@markmc 
> Bug 1898510: This is an manual cherry-pick of #110

- manifests/olm-catalog/4.7/image-references
> Bug 1914869: replace latest for 4.7, so is easier to replace images by ART

- Makefile
- config/manager/kustomization.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
Fix NFD-Operator pod RBAC to prevent it from failing when deploying
nfd-worker
Fixes BZ 1949276
> Bug 1949276: Fix Operator RBAC policies

- controllers/nodefeaturediscovery_resources.go
Adding documentation to describe what each function and var does in the 'controllers/nodefeaturediscovery_resources.go' file. The aim is to assist contributors in understanding how the NFD's resources are processed/interpreted.
> Adding documentation for each function and var related to 'Resources'

- controllers/nodefeaturediscovery_state.go
Adding documentation to describe what each function does in ./controllers/nodefeaturediscovery_state.go does, as well as what
each variable does or what each variable is used for.
> Adding documentation for controller 'state' functions and vars

- controllers/nodefeaturediscovery_controls.go
Adding documentation to describe the functions in the NFD controls file, and to explain how they work and what they're used for.
> Adding documentation for NFD controls

- README.md
Since we have now NFD as part of the official documentation, is time to update and enhance the README to be more dev focused, and all the user focus documentation will be at the openshift official docs page
> Update and enhance README

- OWNERS
My old username was 'cep235', but I recently changed it
to 'courtneypacheco'. I'm updating this file to reflect
my new username.
> Update courtneypacheco github user name on OWNERS file

- manifests/art.yaml
must match the actual CSV filename which is node-feature-discovery-operator.clusterserviceversion.yaml
> art.yaml: match CSV filename

- manifests/4.9/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
> Bug 1992739: Name in CSV not matching art.yaml

- manifests/4.9/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
With which the substitutions from art.yml also yield effect.
> Bug 1995055: Set olm.skipRange in clusterserviceversion.yml

- api/v1/nodefeaturediscovery_types.go
- controllers/nodefeaturediscovery_controller.go
- controllers/nodefeaturediscovery_finalizers.go
- controllers/nodefeaturediscovery_resources.go
The aim of this PR is to add finalizers and related logic to the operator, as part of the level 4 operator cert.
As of right now, the code is very much a WIP and has not been tested thoroughly. I will update the PR when it is in a completed state.
> Add finalizers to the operator

- manifests/4.9/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
> Add olm.skiprange

- README.md
Signed-off-by: Yoni Bettan <ybettan@redhat.com>
> Fixing the CR name to apply nodes labeling in README.md

- manifests/4.8/manifests/nfd-operator_v1_serviceaccount.yaml
> Bug 2026464: NFD operator failing greenwave CVP tests

- Makefile
- manifests/0200_service_account.yaml
> Bug 2026465: NFD operator failing greenwave CVP tests

- README.md
Signed-off-by: Yoni Bettan <ybettan@redhat.com>
> Updating README.md to point to the correct namespace.

- Dockerfile
> Add description label to Dockerfile

- PROJECT
- api/v1/nodefeaturediscovery_types.go
- config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
- config/manifests/bases/nfd.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- controllers/nodefeaturediscovery_controller.go
- controllers/nodefeaturediscovery_controls.go
- controllers/nodefeaturediscovery_finalizers.go
- controllers/nodefeaturediscovery_state.go
- manifests/4.10/bundle.Dockerfile
- manifests/4.10/manifests/nfd.clusterserviceversion.yaml
- manifests/4.10/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
- manifests/4.10/metadata/annotations.yaml
- manifests/art.yaml
Enhance Finalizers checks
Ensure correct package name is nfd not node-feature-discovery-operator as per seen in documentation 
/cc @wabouhamad
> 4.10 last touches

- PROJECT
- api/v1/nodefeaturediscovery_types.go
- config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
- config/default/kustomization.yaml
- config/manifests/bases/nfd.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- controllers/nodefeaturediscovery_controller.go
- controllers/nodefeaturediscovery_controls.go
- controllers/nodefeaturediscovery_finalizers.go
- controllers/nodefeaturediscovery_state.go
- manifests/4.10/bundle.Dockerfile
- manifests/4.10/manifests/nfd.clusterserviceversion.yaml
- manifests/4.10/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
- manifests/4.10/metadata/annotations.yaml
- manifests/art.yaml
> Bug 2048617: Add finalizer status report

- build/assets/master/0200_clusterrole.yaml
> Bug 2055436: Update NodeFeatureRules api group 

- build/assets/topologyupdater/01_sa.yaml
- build/assets/topologyupdater/05_Daemonset.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- controllers/nodefeaturediscovery_controls.go
- main.go
- manifests/4.11/manifests/nfd.clusterserviceversion.yaml
- pkg/config/config.go
> Bug 2042536: Fix SCC control

- main.go
> Bug 2065148: set leader election retry times

- build/assets/topologyupdater/01_sa.yaml
- build/assets/topologyupdater/05_Daemonset.yaml
- config/manager/manager.yaml
- controllers/nodefeaturediscovery_controls.go
- main.go
- manifests/4.10/manifests/nfd.clusterserviceversion.yaml
- pkg/config/config.go
> Bug 2065656: Fix SCC control

- manifests/4.11/manifests/nfd.clusterserviceversion.yaml
- manifests/art.yaml
> Bug 2087511: Fix skipRange

- manifests/4.10/manifests/nfd.clusterserviceversion.yaml
> Bug 2087514: fix SkipRange [release-4.10]

- manifests/4.9/manifests/nfd.clusterserviceversion.yaml
> Bug 2087516: Fix SkipRange [release-4.9]

- .gitignore
- config/manager/kustomization.yaml
- main.go
> Bug 2110005: fix bunle generation

- controllers/nodefeaturediscovery_controls.go
This file currenly uses klog, so changing the log to print
distint messages and errors
Bug-2109861
> Fix the log for controls functions

- controllers/nodefeaturediscovery_controls.go
In case NFD CR are deployed into at least 2 different namespaces,
nfd-master deployment still uses the same ClusterRole and ClusterRoleBinding.
This PR changes the deployment/update of the ClusterRoleBinding by adding
a subject entry for an instance namespace in case there is no subject entry
in ClusterRoleBinding for that namespace
> Fix ClusterRoleBinding confgiuration for multiple namespaces deployment

- OWNERS
> New Owners in the house

- Dockerfile.arm
- Makefile.arm
- README.md
This commit allows build NFD operator ARM image locally (either on and dedicated ARM server, or on local x86-64 machine)
> Adding local ARM compilation/build config

- Dockerfile.cluster-nfd-operator-build
- Makefile
- config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
- config/crd/bases/nfd.openshift.io_v1alpha1_nodefeaturerules.yaml
- config/crd/bases/nfd.openshift.io_v1alpha1_nodefeatures.yaml
- config/crd/kustomization.yaml
- config/manager/kustomization.yaml
> Add NodeFeature CRD to the deployment/bundle and adding new fields

- build/assets/master/0200_clusterrole.yaml
- config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
- config/rbac/role.yaml
- controllers/nodefeaturediscovery_controller.go
- manifests/stable/manifests/nfd.clusterserviceversion.yaml
- manifests/stable/manifests/nfd.openshift.io_nodefeatures.yaml
adding permissions for node listing and for handling nodefeature CRs
> Adding permission to master service account

- Dockerfile
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/bases/nfd.clusterserviceversion.yaml
- config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
- manifests/image-references
- manifests/nfd.package.yaml
- manifests/stable/manifests/nfd.clusterserviceversion.yaml
move all the build files and components to 4.18
> update master branch to 4.18

- Dockerfile.cluster-nfd-operator-build
- Makefile
- config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
- go.mod
- internal/client/client.go
- internal/client/mock_client.go
- internal/configmap/mock_configmap.go
- internal/controllers/mock_nodefeaturediscovery_reconciler.go
- internal/daemonset/mock_daemonset.go
- internal/deployment/mock_deployment.go
- internal/job/mock_job.go
- internal/scc/mock_scc.go
- internal/status/mock_status.go
- vendor/modules.txt
Updating skipper dockefile to use RH image with go 1.23, updating go.mod to use go 1.23, adding mockgen dependency and updating go.sum and vendor directory
> Updating skipper dockerfile and mockgen dependency

- internal/daemonset/daemonset.go
- internal/daemonset/daemonset_test.go
- internal/deployment/deployment.go
- internal/deployment/deployment_test.go
Adding master envs and worker envs to the master deployment and worker daemonset, in case MasterEnvs/WorkerEnvs are defined in the NFD CR
> MasterENVs and WorkerENVs implementations

- config/rbac/gc/clusterrole.yaml
- go.mod
- manifests/stable/manifests/nfd-gc_rbac.authorization.k8s.io_v1_clusterrole.yaml
> adding nf rbac role to gc from d/s group
