openshift/cluster-nfd-operator

Makefile

This is the third Makefile I've seen like this, and as far as I've seen it hasn't hurt to remove the hardcoded GOARCH here. It *does* hurt to leave it in because builds on other architectures simply cross-compile an amd64 binary which is not what we want.
Can you let me know where this Makefile originated? I'd like to fix it at whatever source that may be.

Makefile: remove GOARCH=amd64

---

assets/master/0400_master_daemonset.yaml

For side-car containers to publish labels with custom prefix, one needs to tell the nfd-master to publish those labels explicitly.

Allow additional NVIDIA namespace for labels

---

manifests/olm-catalog/nfd.package.yaml

For the future we want to use a channel name that matches the release it's for.
This is to enable the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1744167

[Bug 1744167] nfd.package.yaml: match OCP channel name

---

assets/worker/0700_worker_daemonset.yaml

NFD worker pods should run on any worker, regardless the toleration an admin/user may put on.

Tolerate only worker nodes for custom taints

---

manifests/olm-catalog/nfd.package.yaml

The channel name should be string in nfd.package.yaml

Bug 1770084: The channel name should be string in nfd.package.yaml

---

manifests/olm-catalog/nfd.package.yaml

The channel name is number, it should be string in nfd.package.yaml

Bug 1772575: The channel name is number, it should be string in nfd.package.yaml

---

manifests/0500_crd.yaml
manifests/olm-catalog/4.4/nfd.crd.yaml

Added `type: object` to description, worked in 4.2 without now needed in 4.3+

Bug 1780678: Added `type: object` to description, worked in 4.2 now needed

---

manifests/0500_crd.yaml
manifests/olm-catalog/4.3/nfd.crd.yaml

Added  to description, worked in 4.2 now needed

Bug 1769455: Added `type:object` to description, worked in 4.2 now needed

---

Makefile
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go

The SCC has a users field where one can specify the ServiceAccount from a specific Namespace to be used. When installing NFD in a non-default namespace, the SCC ServiceAccount namespace has to be updated.

Set the correct namespace for SCC when installed in non default namespace

---

Makefile

Add GO111MODULE=on to `GO_BUILD_RECIPE` on Makefile target `make build`

[release-4.3] Bug 1805175: add GO111MODULE=on

---

Makefile
manifests/0500_crd.yaml
manifests/olm-catalog/4.5/nfd.v4.5.0.clusterserviceversion.yaml

Also now that images are being held on openshift-psap quay, we can change the ORG env var on the Makefile

fix softlink pointing to 4.4 olm

---

manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml

In order for the nfd-operator to be correctly filtered in the
OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.

Bug 1850546: Add support label for s390x & ppc64le

---

manifests/olm-catalog/4.5/nfd.v4.5.0.clusterserviceversion.yaml

In order for the nfd-operator to be correctly filtered in the
OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.
(cherry picked from commit 3d67f5dfca154ba7ce7c4b6a39b6adc7f10e5f5c)

[release-4.5] Bug 1855312: Add support label for s390x & ppc64le

---

Makefile
assets/worker/0700_worker_daemonset.yaml

* Enhance nfd-worker placement
Enable NFD operator to deploy nfd-worker pods on nodes labeled other
than "node-role.kubernetes.io/worker"
*Also: Add clean-labels make target
*Also: some housekeeping to the Makefile

Bug 1868616: Enhance nfd-worker placement

---

manifests/olm-catalog/4.4/nfd.v4.4.0.clusterserviceversion.yaml

In order for the nfd-operator to be correctly filtered in the
OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.
(cherry picked from commit 3d67f5dfca154ba7ce7c4b6a39b6adc7f10e5f5c)

Bug 1855316: Add support label for s390x & ppc64le

---

assets/node-feature-discovery/05-nfd-daemonset.yml
assets/worker/0600_worker_configmap.yaml
assets/worker/0700_worker_daemonset.yaml
manifests/0500_crd.yaml
manifests/0600_operator.yaml
manifests/0700_cr.yaml
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go

Bug 1906129: fix manifest files after  upstream/downstream sync event

---

assets/master/0500_service.yaml
assets/worker/0700_worker_daemonset.yaml

This Patch enables service DNS for the `nfd-master` allowing `nfd-workers` to discover the NFD server without passing an IP  but the service name

Bug 1823765: Enable service DNS for nfd-master

---

cmd/manager/main.go
manifests/0600_operator.yaml

operator sdk was creating a readines file, requiring a VolumeMount from
the host, that is causing seameless uipdtas/upgrades to fail.

Bug 1923998: Remove readines probe from old operator sdk

---

manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml

PR https://github.com/openshift/cluster-nfd-operator/pull/132 removed
the readiness probe from manual manifest deployment, this PR modifies
the CSV that handles the behaviour of the operator when deployed from
operatorhub
This PR also address Bug 1914869

Bug 1923998: Remove readines probe from CSV

---

manifests/0600_operator.yaml

Description of changes:
- By default, the operator deployment is created with RollingUpdate strategy. To avoid hitting Issue #107 this PR declares the `.spec.strategy.type Recreate` field.

added Recreate strategy instead of the default

---

cmd/manager/main.go
manifests/0600_operator.yaml
manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml

operator sdk was creating a readines file, requiring a VolumeMount from
the host, that is causing seameless uipdtas/upgrades to fail.

[release-4.6] Bug 1924232: remove readiness probe from mounting tmp to enable upgrades from OLM

---

cmd/manager/main.go
manifests/0600_operator.yaml
manifests/olm-catalog/4.5/nfd.v4.5.0.clusterserviceversion.yaml

operator sdk was creating a readines file, requiring a VolumeMount from
the host, that is causing seameless uipdtas/upgrades to fail.

[release-4.5] Bug 1924236:  Remove readines probe from old operator sdk

---

manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml

my understanding is this wouldn't upgrade to 4.1.0-> to 4.7.0,
meaning it would miss upgrade in 4.6.z
We saw same issue https://github.com/openshift/cluster-nfd-operator/pull/124/files
and the issue comes from mis-understanding of olm.skipRange.

[release-4.6] Bug 1916007: olm skip range is set to the wrong range

---

pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go

the method init is called everytime the reconcile loop is called,
accumulating states, leading to a cascade of logs.

nodefeaturediscovery_state: avoid accumulating states

---

manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml

Bundle build for cluster-nfd-operator is failing on OSBS. It seems to me that OSBS introduced a check and disallows null values in annotations.
cluster-nfd-operator/manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml
```
Line 15 in 110fdc7
containerImage:  
```
is empty. We need to either give it a value to use an empty string "", though I am not sure if the check will allow empty strings or not.

[release-4.7] Bug 1944242: Update nfd.v4.7.0.clusterserviceversion.yaml

---

manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml

Bundle build for cluster-nfd-operator is failing on OSBS. It seems to me that OSBS introduced a check and disallows null values in annotations.
cluster-nfd-operator/manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
```
Line 15 in 110fdc7
containerImage:
```
is empty. We need to either give it a value to use an empty string "", though I am not sure if the check will allow empty strings or not.

[release-4.6] Bug 1944244: Update nfd.v4.6.0.clusterserviceversion.yaml

---

Makefile

This patch targets BZ 1949102:
NFD-operator fails to build on disconnected environments due to a `go get` command being call by the Makefile on the "build" target

Bug 1949102: Fix image build on disconnected envs

---

Makefile
config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
manifests/0600_operator.yaml
manifests/olm-catalog/4.8/nfd.v4.8.0.clusterserviceversion.yaml

This patch attempts to fix CSV wrong command string

Bug 1952145: cluster-nfd-operator executable file not found in $PATH error 

---

build/assets/node-feature-discovery/05-nfd-daemonset.yml
build/assets/worker/05_worker_ds.yaml

Mount /usr as /host-usr inside the pod to allow NFD to find the kernel
configuration file inside /usr.
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
Addition to https://github.com/openshift/node-feature-discovery/pull/42

Bug 1957846: Mount /usr inside the Pod

---

manifests/4.8/manifests/image-references

This patch adds kube-rbac-proxy image to ART image-references

Bug 1961484: enable art replacement for kube-rbac-proxy image

---

manifests/4.9/manifests/nfd.v4.9.0.clusterserviceversion.yaml

This is necessary for the operator to be displayed in the OperatorHub.

Add support label for arm64

---

main.go

The documentation for the 'health check' flag is nonexistent. This commit aims to describe to contributors what this flag does understand how it works.

Adding documentation for the health check flag in 'main.go'

---

controllers/nodefeaturediscovery_controller.go

The aim of this addition to the documentation is to describe to contributors how the reconciliation functions and struct work for the controller, while also describing their importance.

Adding documentation for the controller reconciliation funcs and struct

---

main.go

The documentation for the 'enable leader election' flag is nonexistent. This commit serves the purpose of adding documentation for this flag so that users and contributors both understand how it works, and it also serves the purpose of describing what the default flag value means.

Adding documentation for the leader election flag in 'main.go'

---

main.go

Prometheus is used to scrape data (metrics) in relation to NFD resource usage. It is important for contributors to know and understand what 'metrics bind address' is and how it relates to this data scraping. It is also important for contributors to see how the metrics scraping bind address relates to the manifests under './manifests' and './config'.

Updating documentation in 'main.go' for 'metricsAddr'

---

controllers/nodefeaturediscovery_resources.go
controllers/nodefeaturediscovery_state.go

Adding documentation for structs defined in the two files in this commit. This documentation describes the fields within these structs so that contributors know what each field means and what each field does. These structs are used quite a bit in other .go files, and so it is important for contributors to be able to understand these structs.

Adding documentation for NFD related structs (types)

---

controllers/nodefeaturediscovery_controller.go
controllers/nodefeaturediscovery_status.go

Add "Requeue: true" to the reconcile return values to force the
reconciler to rerun after a resource is degraded or progressing.
This is preferred over throwing an error message in the return
value of the Reconcile function.
Additionally, fix the status message for the master daemonset, as
it was referring to the worker daemonset and not the master
daemonset.

Bug 1985465: Fix error messages that occur after degraded and progressing resources

---

api/v1/nodefeaturediscovery_types.go
config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
manifests/4.8/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml

Patch based on https://github.com/openshift/cluster-nfd-operator/pull/187 with minor changes to accommodate to past release, automated cherry-pick was not possible due to newer changes on current release 

Bug 1986570: drop operand images as required field on CRD

---

controllers/nodefeaturediscovery_controller.go

The existing error checking library, `criapierrors`, was used to check for the case where the NFD instance is deleted. However, this error checking library is used for GRPC specific errors, not for errors related to the `metav1` package. The `metav1` package is used by various OCP resources (e.g., DaemonSet, Service, etc.), and thus, we should be checking for `metav1` problems, not GRPC problems. (Note: If we only check for GRPC problems, the `criapierrors` package will not be able to detect a deleted NFD instance. This is because a deleted resource will have `metav1` attributes empty or pointers set to `nil`.)

Use apimachinery error library to check for missing nfd instances

---

controllers/nodefeaturediscovery_controller.go

The NFD Operator attempts to check if one or more of its resources have been updated by determining whether or not a recorded event has "old" and "new" versions of the same resources. However, the logic should not end there. The Operator should also determine if the old and new versions are *actually* different. In other words, the operator may see "two versions" of the same resource and thus think that a change occurred, but both "versions" of the resource *may actually be identical*, which means an update didn't actually occur. So, we want to make sure that the operator's reconciler doesn't attempt to update something that doesn't need updating, as we don't want the reconciler unnecessarily being called multiple times when no update is required.

Fix the controller manager's logic for updating resources

---

controllers/nodefeaturediscovery_controller.go
controllers/nodefeaturediscovery_status.go

Currently, the same logic is being used for updating the NFD instance CR, as well as adding and removing finalizers. However, the code for this logic is repeated. Thus, the aim of this PR is to consolidate the code so that the logic is not repeated, but instead reused for all situations.
Note that I also added code to check for master and worker service accounts, as the previous PR for updating the NFD CRD status only checked for the master service account, not the worker service account too.
Finally, I also added code to initialize a resource's status to "isDegraded" instead of having the same code repeated a number of times in the `controllers/nodefeaturediscovery_status.go` code.

Consolidate code for finalizers and CR status updates

---

config/prometheus/monitor.yaml
manifests/4.9/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml

This line is causing:
Error: Value controller-manager-alerts-monitor: error validating object:
metadata.namespace: Forbidden: not allowed on this type.

Bug 2009812: Remove namespace from controller-manager-alerts-monitor

---

manifests/image-references

This PR fixes the kube-rbac-proxy image reference used by the NFD Operator. Without this fix, the image is referenced by an implicit `latest` tag, and this breaks disconnected deployment, which requires a SHA image reference.
`registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.10` is the string [used](https://github.com/openshift/cluster-nfd-operator/blob/c8d4be46e46622f1f29479cedac4a020d73bc08b/manifests/image-references) in `manifests/image-reference` for the `kube-rbac-proxy` image. This string will be replaced (by ART) by the image+SHA.
WARNING: I'm not sure how to test this :(

CSV: fix kube-rbac-proxy image reference

---

manifests/4.10/manifests/nfd-operator_v1_serviceaccount.yaml

OLM manages the lifecycle of the serviceaccount which is specified in
the CSV.
If it's added again as a separate manifest it may interfere and cause
issues with OLM’s management process (like causing upgrade failures
etc). That's the reason it need not be added by the user separately.
The suggested action is to remove the service account config yaml file
from the operator’s manifest folder.

Bug 2022496: NFD operator failing greenwave CVP tests

---

manifests/4.9/manifests/nfd-operator_v1_serviceaccount.yaml

OLM manages the lifecycle of the serviceaccount which is specified in
the CSV.
If it's added again as a separate manifest it may interfere and cause
issues with OLM’s management process (like causing upgrade failures
etc). That's the reason it need not be added by the user separately.
The suggested action is to remove the service account config yaml file
from the operator’s manifest folder.

Bug 2022518: NFD operator failing greenwave CVP tests

---

config/manager/manager.yaml
config/manifests/bases/nfd.clusterserviceversion.yaml
config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
manifests/4.11/manifests/nfd.clusterserviceversion.yaml

In Telco far edge use case, a cluster might have limited management bandwidth.
Upgrading such a cluster is expected to be time-limited (capped by a maintenance window) and will involve container image pre-caching on the node.
Image pre-caching solution for nodes with limited management bandwidth relies on the assumption, that workloads can use locally stored images without contacting a registry.  This is possible if the container image pull policy is set to "IfNotPresent".
The NFD operator is using Always as the pull policy, we should delete the policy and have the default behavior.
From https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
When you (or a controller) submit a new Pod to the API server, your cluster sets the image pull policy field when specific …

Bug 2055049: Do not set explicitly image pull policy to Always

---

config/manager/manager.yaml
config/manifests/bases/nfd.clusterserviceversion.yaml
config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
manifests/4.10/manifests/nfd.clusterserviceversion.yaml

In Telco far edge use case, a cluster might have limited management bandwidth.
Upgrading such a cluster is expected to be time-limited (capped by a maintenance window) and will involve container image pre-caching on the node.
Image pre-caching solution for nodes with limited management bandwidth relies on the assumption, that workloads can use locally stored images without contacting a registry. This is possible if the container image pull policy is set to "IfNotPresent".
The NFD operator is using Always as the pull policy, we should delete the policy and have the default behavior.
From https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
When you (or a controller) submit a new Pod to the API server, your cluster sets the image pull policy field when specific …

[release-4.10] Bug 2055244: Do not set explicitly image pull policy to Always

---

Dockerfile
config/manifests/bases/nfd.clusterserviceversion.yaml
manifests/4.11/manifests/nfd.clusterserviceversion.yaml
pkg/config/config.go
version/version.go

The image-references must exactly match in order for ART substitutions to take place.
/cc @ArangoGutierrez

Bug 2089962: update version to 4.11

---

controllers/nodefeaturediscovery_finalizers.go

This PR removes the update predicate that checks for the change of the `.metadata.generation` field of the NFD CR, in order to be able to fully reconcile a created NFD CR after its finalizer and status is updated.
According to the Kubernetes documentation, `.metadata` or `.status` updates do not bump the `.metadata.generation` of an object. This leads to the NFD CR not being fully reconciled after its creation, i.e. after the addition of its finalizer and the update of its `.status`, there is no additional update reconciliation event queued. The cause is the update predicate used to check for the difference between the `.metadata.generation` field of the old and new NFD objects.
This issue cannot be reproduced using `kubectl` (not sure yet why that is), but it is reproducible by using a …

Remove generation check in NFD update predicate

---

controllers/nodefeaturediscovery_controls.go

In case NFD instance is deployed into a different namespace than the one
that operator is deployed into (openshift-nfd), ServiceAccount will also be deployed
into the new namespace.Therefore, RoleBinding should point to the new namespace in its
Subjects field, and not to a default one (openshift-nfd)
Bug-2110333

Fix the RoleBinding configuration for different namespaces deployment

---

controllers/nodefeaturediscovery_finalizers.go
controllers/nodefeaturediscovery_resources.go

This PR includes 3 issues:
1) in case of multi namespace scenario, ClusterRole, ClusterRoleBinding
and SCC are not removed during finalization in case there is another
NFD CR in a different namespace still present
2) code refactoring for components deletion
3) change Poll to PollImmidiate during componets deletion - reduces
time needed for CR deletion

Fix CR finalization in multiple namespaces scenario

---

main.go

This PR allows supporting different NFD CRs in the running cluster. Currently NFD supports only one NFD CRs per namespace, and it only watches the namespace it was deployed into. This PR supplies the final brick to allow deploying additional NFD CRs, each one in its own namespace. 1) NFD operator should watch cluster-wide namespaces 2) on each new CR a master/worker will be deployed in the
correlated namespace, with the appropriate Role/RoleBinding
3) NFD will rely on the ClusterRole/ClusterRoleBinding/SCC
deployed by the first CR
This implementation will probably be changed in the future, once we consolidate multiple CRs issues in the upstream.

Allow multiple NFD CR in the cluster

---

Makefile

This change replaces `go get` with `go install` to install the binaries used in various Makefile rules, as from Go 1.18 onwards `go get` no longer builds packages.
- https://go.dev/doc/go-get-install-deprecation
Signed-off-by: Michail Resvanis <mresvani@redhat.com>

Replace deprecated `go get` in Makefile

---

Makefile

Makefile has moved from "go get" to "go install" method of installing needed packages, including kustomize. Kustomize version needs to be updated to a newer one, where go.mod does not include replace/exclude directives

Changing kustomize version

---

config/manager/manager.yaml

Starting from 4.12 the openshift-nfd namespace needs a label to allow pod security privilidged level for nfd worker In case NFD is deployed to a different namespace, OCP operator will add the needed label ( it ignores all namespaces starting with openshift)

Adding pod security label for NFD namespace

---

Makefile

ART is running in disconnected environment. build target was depended on go_mod target which executes go mod download. In order for ART to use vendor directory as is, build must not depend on go_mod

Fixing ART build failure in Makefile

---

Makefile

ART is running in disconnected environment. build target was depended on go_mod target which executes go mod download. In order for ART to use vendor directory as is, build must not depend on go_mod

OCPBUGS-4296:Fixing ART build failure in Makefile

---

config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
config/crd/bases/nfd.openshift.io_v1_nodefeaturediscoveries.yaml
config/rbac/role.yaml
manifests/4.12/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml

Currently NFD controller expect the topology flag json tag to be "topologyUpdater". The yaml that is used during deployment is using the old annotation: "topologyupdater". In order to fix, we need to allign the nfd.openshift.io_v1_nodefeaturediscoveries.yaml with the nfd.openshift.io_nodefeaturediscoveries.yaml

Fixing the discrepency between the NFD yaml and the API

---

controllers/nodefeaturediscovery_finalizers.go

In case Topology is enabled, deleting NFD CR will stuck, because validation if all the resources have been deleted fill fail, due to topology SCC still being present in the cluster This PR add deletion of topology SCC in the finalizers

Fixing NFD CR deletion in case of Topology enablement

---

controllers/nodefeaturediscovery_status.go

Fixes OCPBUGS-8708
In the release-4.11 branch the status.conditions[].message  and  status.conditions[].reason  fields are optional and not populated, but in release-4.12 they are mandatory causing an upgrade from 4.11->4.12 to fail.
This PR sets these fields in 4.11 (while leaving them optional) to default values allowing 4.12 to make them mandatory.

OCPBUGS-8708: ensure currently optional status fields are populated #320

---

main.go
manifests/stable/manifests/nfd.clusterserviceversion.yaml

Since we NFD configuration now supports only single namespace deployment, manager configuration must be watching a specific namespace only, and not all-cluster namespaces

aligning manager watch config with single namespace

---

build/assets/topologyupdater/04_configmap.yaml
build/assets/topologyupdater/05_Daemonset.yaml
controllers/nodefeaturediscovery_controls.go

1) mapping host's device-plugins directory into pod, since it is
needed now by the kubelet notifier
2) adding topology configmap to the build/assests
3) fixing handling/creation of configmap in the operator. currently it
is hardcoded supporting only nfd-worker configmap, and this PR
allows supporting of addition configmaps

Fixing topology pod creation failure

---

config/default/manager_auth_proxy_patch.yaml
config/manifests/bases/nfd.clusterserviceversion.yaml
manifests/stable/manifests/nfd.clusterserviceversion.yaml

This PR is a response to the customer's request to suppress some elaborate debug log in the kube-rbac-proxy container

Lowering the verbosity of kube-rbac-proxy container

---

config/manifests/bases/nfd.clusterserviceversion.yaml
manifests/stable/manifests/nfd.clusterserviceversion.yaml

the docs link in the bundle still points to the 4.9 docs and the contact email pointed to openShift-psap@redhat.com this PR changes that to the 4.15 docs

OCPBUGS-22728 update the docs link & email

---

config/manager/manager.yaml
config/manifests/bases/nfd.clusterserviceversion.yaml
config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
manifests/image-references
manifests/nfd.package.yaml
manifests/stable/manifests/nfd.clusterserviceversion.yaml
pkg/config/config.go

there are references to the old 4.15 in the 4.16 manifests etc, this PR replaces them with the correct 4.16 version.

replace old version numbers with the correct 4.16

---

controllers/nodefeaturediscovery_finalizers.go
controllers/nodefeaturediscovery_status.go
pkg/utils/utils.go

Backport #316 to the 4.12 branch
for some reason we have a fix in 4.11, 4.13, and later but not 4.12, which has caused some issues for customsers. this backport fixes that
Original message:
Fix the absence of status from NFD CR
Since moving the NFD CR status to use the apimachinery conditions, the reason fields has become non-empty mandatory field. Since it is not set, the update to status is failing, and therefore status is not shown , since it has never been updated.
This PR adds Reason field values to all the conditions
OCPBUGS-7023

OCPBUGS-32047: Fix the absence of status from NFD CR (backport PR316)

---

config/crd/kustomization.yaml

the kustomization yaml must be fixed in order to support the new files' names for crds

fixing bundle creation

---

manifests/stable/manifests/nfd.openshift.io_nodefeaturerules.yaml

The NodeFeatureRules implementation and docs includes the ability to set `extendedResources`, `annotations`, and `taints` based on matches. The CRD supplied with the release-4.15 operator does not include them, so they are impossible to set in openshift. This backports the master CRD definition (where they are set) back to 4.15.

OCPBUGS-32940: backport the extendedResources etc fields into the rules CRD

---

manifests/stable/manifests/nfd.openshift.io_nodefeaturerules.yaml

The 4.14 nodefeaturerules crd for the operator is missing the extendedResources and taints fields even though they are supported in the 4.14 operand (and are in the docs). This PR backports those fields from the CRD in master.

OCPBUGS-31488: backport the extendedResources and taint fields into the rules CRD

---

manifests/stable/manifests/nfd.clusterserviceversion.yaml

in manifests/image-references we're set to replace
> quay.io/openshift/origin-cluster-nfd-operator:4.16
with the image built by ART, but in the csv nfd.clusterserviceversion.yaml we have
>image: quay.io/openshift/origin-cluster-nfd-operator:4.16.0
(with an added .0).
Because they differ the CSV is not getting that image updated, so anything installingthe csv is defaulting to an old image that exists for x64 but not for POWER, causing nfd deployments on ppc64le and s390x to fail.

OCPBUGS-33287: set the image to match what art will replace (in image-references)

---

config/crd/bases/nfd.openshift.io_v1alpha1_nodefeaturerules.yaml

change to config/crd/bases/nfd.openshift.io_v1alpha1_nodefeaturerules.yaml  adding support for extendedResources and Taints  these changes were  made in  #348  (commit  f136eef)   and were backported into release-4.15 but never made it into 4.14.
This PR backports those changes. 
This is needed for [OCPBUGS-31488](https://issues.redhat.com/browse/OCPBUGS-31488) and were missed in #368

OCPBUGS-31488: add node-feature-rules crd changes from #348 to config

---

api/v1/nodefeaturediscovery_types.go
config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
controllers/nodefeaturediscovery_controls.go
manifests/stable/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml

This adds a new option to the NodeFeatureDiscoverySpec `Spec.enableTaints`  when this is set to true it will add the `--enable-taints` flag to the master, allowing NFD to set taints as described in the [upstream docs](https://kubernetes-sigs.github.io/node-feature-discovery/master/usage/customization-guide.html?highlight=Taints#taints)
This option is disabled by default, and not set in the sample configs, as taints support is experimental.

OCPBUGS-33741: add the enableTaints option to the discovery resource

---

config/crd/bases/nfd.openshift.io_nodefeaturerules.yaml
config/crd/bases/nfd.openshift.io_nodefeatures.yaml

nf cr could not be created on initial deployment due to different versions between the repos, this pr fixes it

changing nf crd version from v1 to v1alpha1 

---

manifests/image-references
manifests/stable/manifests/nfd.clusterserviceversion.yaml

the kube-rbac-proxy image name that ART is updating when building bundles (defined in manifests/image-references) and the version we are setting in the manifest are out of sync and are both wrong. This PR replaces them both with  `registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9:v4.16`  which should allow ART to build the bundle correctly and allow it to work with disconnected environments.
It uses the v4.16 version because as yet there is no 4.17 version of the kube-proxy released.
(see #220 for more details)

update the kube-rbac-proxy pullspec to ocp version

---

manifests/image-references
manifests/stable/manifests/nfd.clusterserviceversion.yaml

backport #382 382 to 4.17
set the kube-proxy image in the csv to registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9:v4.16
(see https://github.com/openshift/cluster-nfd-operator/pull/220 for more details)

OCPBUGS-39177: change proxy to ose-kube-rbac-proxy-rhel9:v4.16

---

manifests/image-references
manifests/stable/manifests/nfd.clusterserviceversion.yaml

backport #382 to 4.16
set the kube-proxy image in the csv to  registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9:v4.16 
(see https://github.com/openshift/cluster-nfd-operator/pull/220 for more details)

OCPBUGS-38239: change proxy to ose-kube-rbac-proxy-rhel9:v4.16

---

config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy/service.yaml
manifests/stable/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
manifests/stable/manifests/nfd-controller-manager-metrics-service_v1_service.yaml
manifests/stable/manifests/nfd.clusterserviceversion.yaml

in 4.17 we have changed the labelling of control plane in deployment and various other object which causes upgrade issues, since labels are immutable. This PR changes the contol-plane labels' values back to the values we had in 4.16

Fixing upgrade from 4.16 to 4.17

---

config/manifests/bases/nfd.clusterserviceversion.yaml
manifests/stable/manifests/nfd.clusterserviceversion.yaml

This commit removes the image field from the ClusterServiceVersion resource annotation to ensure that olm-deployed crs do not include it by default.
---
This PR is a follow-up for #396
/cc @yevgeny-shnaidman @ybettan

Removing image from clusterserviceversion

---

.ci-operator.yaml
Dockerfile
config/manager/kustomization.yaml
config/manager/manager.yaml
config/manifests/bases/nfd.clusterserviceversion.yaml
manifests/image-references
manifests/nfd.package.yaml
manifests/stable/manifests/nfd.clusterserviceversion.yaml

Fix CSV validation by ART; currently failing with:
```
Bundle cluster-nfd-operator-metadata-container-v4.19.0.202503031239.p0.ga3de6d9.assembly.stream.el9-2 CSV metadata.name has no datestamp: nfd.v4.18.0
Bundle cluster-nfd-operator-metadata-container-v4.19.0.202503031239.p0.ga3de6d9.assembly.stream.el9-2 CSV spec.version has no datestamp: 4.18.0
```
Incorporates https://github.com/openshift/cluster-nfd-operator/pull/408

OCPBUGS-52218: Fix 4.19 CSV references

---

internal/daemonset/daemonset.go
internal/daemonset/testdata/test_topology_daemonset.yaml
internal/daemonset/testdata/test_worker_daemonset.yaml
internal/deployment/deployment.go
internal/deployment/testdata/test_gc_deployment.yaml
internal/deployment/testdata/test_master_deployment.yaml

In OCP the dns policy field not be set, which will make OCP assign it to the Default dns policy

Fixing the DNS policy of the operand

---

internal/daemonset/daemonset.go
internal/daemonset/worker.go
internal/daemonset/worker_test.go
internal/deployment/deployment.go
internal/deployment/deployment_test.go

This commit add tolerations defined in the WorkerTolerations field of the NFD CR to the worker daemonset tolerations definition.It also does the same for master deployment based on the MasterTolerations field of the NFD CR

Adding tolerations implementation to master and worker pod

---

internal/deployment/deployment.go
internal/deployment/testdata/test_master_deployment.yaml

1. Changing the liveness and Readiness probes to use the same http pod
2. Adding the StartupProbe to support large clusters configuration
3. Adding port configuration to support all 3 probes

Changing the Probes of the operator pod

---

config/rbac/gc/clusterrole_binding.yaml
config/rbac/prune/clusterrole_binding.yaml
config/rbac/topologyupdater/clusterrole_binding.yaml
manifests/stable/manifests/nfd-prune_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
manifests/stable/manifests/nfd-topology-updater_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml

Fixing the clusterrolebindins of prune and topology-updater to point to the appropriate SA in the correct (openshift-nfd) namespaces

Fixing the clusterrolebindings for prune and topology

---

manifests/stable/manifests/nfd-master_rbac.authorization.k8s.io_v1_clusterrole.yaml
manifests/stable/manifests/nfd-worker_rbac.authorization.k8s.io_v1_role.yaml

ART bundle is built from the manifests directory. This commit updates the master cluster and worker role in the manifests directory

Fixing official bundle generation

---

api/v1/nodefeaturediscovery_types.go
config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go
internal/daemonset/testdata/test_worker_daemonset.yaml
manifests/stable/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml

This commit adds a field WorkerNodeSelector to the NFD CR that allows user to defined on which worker nodes the NFD worker pods should be scheduled

Adding node selector option for the worker pods
